-- Run this once in the Supabase SQL Editor.
-- Create an Auth user for each administrator, then set app_metadata.role = "admin".

-- events.id stays an independent autoincrement key with no foreign links.
-- events.event_id is the application's event key; registrations reference it.
ALTER TABLE public.events
    ADD COLUMN IF NOT EXISTS time text,
    ADD COLUMN IF NOT EXISTS recurrence text,
    ADD COLUMN IF NOT EXISTS "maxParticipants" integer NOT NULL DEFAULT 50,
    ADD COLUMN IF NOT EXISTS event_id bigint,
    ADD COLUMN IF NOT EXISTS created_by uuid DEFAULT auth.uid() REFERENCES auth.users (id) ON DELETE SET NULL;

UPDATE public.events SET event_id = id WHERE event_id IS NULL;

ALTER TABLE public.events
    ALTER COLUMN event_id SET NOT NULL,
    ALTER COLUMN recurrence DROP NOT NULL,
    ALTER COLUMN created_at SET DEFAULT now();

DO $$
DECLARE
    target_column text;
    sequence_name text;
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM pg_constraint
        WHERE conname = 'events_event_id_key'
          AND conrelid = 'public.events'::regclass
    ) THEN
        ALTER TABLE public.events
            ADD CONSTRAINT events_event_id_key UNIQUE (event_id);
    END IF;

    FOREACH target_column IN ARRAY ARRAY['id', 'event_id'] LOOP
        IF NOT EXISTS (
            SELECT 1
            FROM information_schema.columns AS columns
            WHERE columns.table_schema = 'public'
              AND columns.table_name = 'events'
              AND columns.column_name = target_column
              AND (columns.is_identity = 'YES' OR columns.column_default IS NOT NULL)
        ) THEN
            EXECUTE format(
                'ALTER TABLE public.events ALTER COLUMN %I ADD GENERATED BY DEFAULT AS IDENTITY',
                target_column
            );
        END IF;

        sequence_name := pg_get_serial_sequence('public.events', target_column);
        IF sequence_name IS NOT NULL THEN
            EXECUTE format(
                'SELECT setval(%L, coalesce((SELECT max(%I) FROM public.events), 1), EXISTS (SELECT 1 FROM public.events))',
                sequence_name, target_column
            );
        END IF;
    END LOOP;

    ALTER TABLE public.events DROP CONSTRAINT IF EXISTS events_recurrence_check;
    ALTER TABLE public.events
        ADD CONSTRAINT events_recurrence_check
        CHECK (recurrence IS NULL OR recurrence IN ('daily', 'weekly', 'monthly', 'yearly'));
END
$$;

CREATE TABLE IF NOT EXISTS public.birthdays (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    date date NOT NULL,
    name text NOT NULL CHECK (length(trim(name)) BETWEEN 1 AND 120)
);

CREATE TABLE IF NOT EXISTS public.holidays (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    date text NOT NULL CHECK (
        date ~ '^(0[1-9]|1[0-2])-(0[1-9]|[12][0-9]|3[01])$'
        AND to_char(to_date(date, 'MM-DD'), 'MM-DD') = date
    ),
    name text NOT NULL CHECK (length(trim(name)) BETWEEN 1 AND 120),
    event_type text NOT NULL DEFAULT 'general'
        CHECK (event_type IN ('general', 'moto'))
);

CREATE TABLE IF NOT EXISTS public.event_registrations (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    event_id bigint NOT NULL
        REFERENCES public.events(event_id) ON DELETE CASCADE,
    registration_key uuid NOT NULL,
    name text NOT NULL CHECK (length(trim(name)) BETWEEN 1 AND 120),
    contact text NOT NULL DEFAULT 'не указан' CHECK (length(contact) <= 200),
    notes text NOT NULL DEFAULT '' CHECK (length(notes) <= 2000),
    registered_at timestamptz NOT NULL DEFAULT now(),
    UNIQUE (event_id, registration_key)
);

-- Legacy layout: events.id referenced event_registrations.id, so the old registration
-- id is the event id (events.event_id was filled from events.id above).
ALTER TABLE public.event_registrations
    ADD COLUMN IF NOT EXISTS event_id bigint;

DO $$
DECLARE
    old_fk record;
    legacy_found boolean := false;
    sequence_name text;
BEGIN
    -- Legacy: events.id referenced event_registrations.id (events_id_fkey). Remove it so
    -- events.id has no foreign links and events can be saved without a registration row.
    FOR old_fk IN
        SELECT c.conname, false AS on_id
        FROM pg_constraint AS c
        WHERE c.conrelid = 'public.events'::regclass
          AND c.confrelid = 'public.event_registrations'::regclass
          AND c.contype = 'f'
    LOOP
        EXECUTE format('ALTER TABLE public.events DROP CONSTRAINT %I', old_fk.conname);
        legacy_found := true;
    END LOOP;

    FOR old_fk IN
        SELECT c.conname,
               c.conkey = ARRAY[
                   (SELECT attnum FROM pg_attribute
                    WHERE attrelid = c.conrelid AND attname = 'id' AND NOT attisdropped)
               ]::smallint[] AS on_id
        FROM pg_constraint AS c
        WHERE c.conrelid = 'public.event_registrations'::regclass
          AND c.confrelid = 'public.events'::regclass
          AND c.contype = 'f'
    LOOP
        EXECUTE format('ALTER TABLE public.event_registrations DROP CONSTRAINT %I', old_fk.conname);
        IF old_fk.on_id THEN
            legacy_found := true;
        END IF;
    END LOOP;

    -- In the legacy layout a registration's id equals the id of its event.
    IF legacy_found THEN
        UPDATE public.event_registrations AS registrations
        SET event_id = registrations.id
        WHERE registrations.event_id IS NULL
          AND EXISTS (
              SELECT 1 FROM public.events AS events
              WHERE events.event_id = registrations.id
          );
    END IF;

    IF NOT EXISTS (SELECT 1 FROM public.event_registrations WHERE event_id IS NULL) THEN
        ALTER TABLE public.event_registrations ALTER COLUMN event_id SET NOT NULL;
    END IF;

    IF NOT EXISTS (
        SELECT 1
        FROM information_schema.columns AS columns
        WHERE columns.table_schema = 'public'
          AND columns.table_name = 'event_registrations'
          AND columns.column_name = 'id'
          AND (columns.is_identity = 'YES' OR columns.column_default IS NOT NULL)
    ) THEN
        ALTER TABLE public.event_registrations ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY;
    END IF;

    sequence_name := pg_get_serial_sequence('public.event_registrations', 'id');
    IF sequence_name IS NOT NULL THEN
        PERFORM setval(
            sequence_name,
            coalesce((SELECT max(id) FROM public.event_registrations), 1),
            EXISTS (SELECT 1 FROM public.event_registrations)
        );
    END IF;

    ALTER TABLE public.event_registrations
        ADD CONSTRAINT event_registrations_event_id_fkey
        FOREIGN KEY (event_id) REFERENCES public.events(event_id) ON DELETE CASCADE;
END
$$;

CREATE UNIQUE INDEX IF NOT EXISTS event_registrations_event_key_idx
    ON public.event_registrations (event_id, registration_key);

CREATE INDEX IF NOT EXISTS event_registrations_event_id_idx
    ON public.event_registrations (event_id);

CREATE OR REPLACE FUNCTION public.is_buhlo_admin()
RETURNS boolean
LANGUAGE sql
STABLE
AS $$
    SELECT coalesce(auth.jwt() -> 'app_metadata' ->> 'role' = 'admin', false);
$$;

CREATE TABLE IF NOT EXISTS public.user_profiles (
    id uuid PRIMARY KEY REFERENCES auth.users (id) ON DELETE CASCADE,
    username text UNIQUE,
    role text NOT NULL DEFAULT 'user' CHECK (role IN ('user', 'admin')),
    created_at timestamptz NOT NULL DEFAULT now()
);

DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1
        FROM pg_constraint
        WHERE conrelid = 'public.user_profiles'::regclass
          AND conname = 'user_profiles_username_length'
    ) THEN
        ALTER TABLE public.user_profiles
            ADD CONSTRAINT user_profiles_username_length
            CHECK (username IS NULL OR char_length(btrim(username)) BETWEEN 2 AND 40)
            NOT VALID;
    END IF;
END
$$;

ALTER TABLE public.user_profiles ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON public.user_profiles FROM anon, authenticated;
GRANT SELECT ON public.user_profiles TO authenticated;

DO $$
DECLARE
    old_policy record;
BEGIN
    FOR old_policy IN
        SELECT policyname
        FROM pg_policies
        WHERE schemaname = 'public'
          AND tablename = 'user_profiles'
    LOOP
        EXECUTE format('DROP POLICY %I ON public.user_profiles', old_policy.policyname);
    END LOOP;
END
$$;

CREATE POLICY "Users read own profile"
    ON public.user_profiles FOR SELECT TO authenticated
    USING (id = (SELECT auth.uid()));

INSERT INTO public.user_profiles (id, role)
SELECT
    users.id,
    CASE WHEN users.raw_app_meta_data ->> 'role' = 'admin' THEN 'admin' ELSE 'user' END
FROM auth.users AS users
ON CONFLICT (id) DO NOTHING;

CREATE OR REPLACE FUNCTION public.create_user_profile()
RETURNS trigger
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = ''
AS $$
BEGIN
    INSERT INTO public.user_profiles (id, username, role)
    VALUES (
        NEW.id,
        nullif(btrim(NEW.raw_user_meta_data ->> 'username'), ''),
        CASE WHEN NEW.raw_app_meta_data ->> 'role' = 'admin' THEN 'admin' ELSE 'user' END
    )
    ON CONFLICT (id) DO NOTHING;
    RETURN NEW;
END;
$$;

REVOKE ALL ON FUNCTION public.create_user_profile() FROM PUBLIC, anon, authenticated;
DROP TRIGGER IF EXISTS create_user_profile_after_signup ON auth.users;
CREATE TRIGGER create_user_profile_after_signup
    AFTER INSERT ON auth.users
    FOR EACH ROW EXECUTE FUNCTION public.create_user_profile();

ALTER TABLE public.events ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.birthdays ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.holidays ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.event_registrations ENABLE ROW LEVEL SECURITY;

DO $$
DECLARE
    old_policy record;
BEGIN
    FOR old_policy IN
        SELECT schemaname, tablename, policyname
        FROM pg_policies
        WHERE schemaname = 'public'
          AND tablename IN ('events', 'birthdays', 'holidays', 'event_registrations')
    LOOP
        EXECUTE format(
            'DROP POLICY %I ON %I.%I',
            old_policy.policyname,
            old_policy.schemaname,
            old_policy.tablename
        );
    END LOOP;
END
$$;

REVOKE ALL ON public.events, public.birthdays, public.holidays, public.event_registrations
    FROM anon, authenticated;
GRANT SELECT ON public.events, public.birthdays, public.holidays TO anon, authenticated;
GRANT INSERT, UPDATE, DELETE ON public.events, public.birthdays, public.holidays TO authenticated;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.event_registrations TO authenticated;

DO $$
DECLARE
    sequence_name text;
BEGIN
    sequence_name := pg_get_serial_sequence('public.events', 'id');
    IF sequence_name IS NOT NULL THEN
        EXECUTE format('GRANT USAGE, SELECT ON SEQUENCE %s TO authenticated', sequence_name);
    END IF;
    sequence_name := pg_get_serial_sequence('public.events', 'event_id');
    IF sequence_name IS NOT NULL THEN
        EXECUTE format('GRANT USAGE, SELECT ON SEQUENCE %s TO authenticated', sequence_name);
    END IF;
    sequence_name := pg_get_serial_sequence('public.birthdays', 'id');
    IF sequence_name IS NOT NULL THEN
        EXECUTE format('GRANT USAGE, SELECT ON SEQUENCE %s TO authenticated', sequence_name);
    END IF;
    sequence_name := pg_get_serial_sequence('public.holidays', 'id');
    IF sequence_name IS NOT NULL THEN
        EXECUTE format('GRANT USAGE, SELECT ON SEQUENCE %s TO authenticated', sequence_name);
    END IF;
    sequence_name := pg_get_serial_sequence('public.event_registrations', 'id');
    IF sequence_name IS NOT NULL THEN
        EXECUTE format('GRANT USAGE, SELECT ON SEQUENCE %s TO authenticated', sequence_name);
    END IF;
END
$$;

REVOKE ALL ON FUNCTION public.is_buhlo_admin() FROM PUBLIC;
GRANT EXECUTE ON FUNCTION public.is_buhlo_admin() TO anon, authenticated;

DROP POLICY IF EXISTS "Public can read events" ON public.events;
CREATE POLICY "Public can read events"
    ON public.events FOR SELECT TO anon, authenticated USING (true);
DROP POLICY IF EXISTS "Admins manage events" ON public.events;
CREATE POLICY "Admins manage events"
    ON public.events FOR ALL TO authenticated
    USING (public.is_buhlo_admin()) WITH CHECK (public.is_buhlo_admin());
DROP POLICY IF EXISTS "Members add events" ON public.events;
CREATE POLICY "Members add events"
    ON public.events FOR INSERT TO authenticated
    WITH CHECK (
        created_by = (SELECT auth.uid())
        AND length(btrim(title)) BETWEEN 1 AND 120
        AND (time IS NULL OR time ~ '^([01][0-9]|2[0-3]):[0-5][0-9]$')
        AND length(coalesce(location, '')) <= 240
        AND length(coalesce(description, '')) <= 2000
        AND (recurrence IS NULL OR recurrence IN ('daily', 'weekly', 'monthly', 'yearly'))
        AND "maxParticipants" BETWEEN 1 AND 500
    );
DROP POLICY IF EXISTS "Members edit own events" ON public.events;
CREATE POLICY "Members edit own events"
    ON public.events FOR UPDATE TO authenticated
    USING (created_by = (SELECT auth.uid()))
    WITH CHECK (
        created_by = (SELECT auth.uid())
        AND length(btrim(title)) BETWEEN 1 AND 120
        AND (time IS NULL OR time ~ '^([01][0-9]|2[0-3]):[0-5][0-9]$')
        AND length(coalesce(location, '')) <= 240
        AND length(coalesce(description, '')) <= 2000
        AND (recurrence IS NULL OR recurrence IN ('daily', 'weekly', 'monthly', 'yearly'))
        AND "maxParticipants" BETWEEN 1 AND 500
    );

-- Non-admin users may not change an event's key or owner.
CREATE OR REPLACE FUNCTION public.guard_event_update()
RETURNS trigger
LANGUAGE plpgsql
SET search_path = ''
AS $$
BEGIN
    IF (SELECT auth.uid()) IS NOT NULL AND NOT public.is_buhlo_admin()
       AND (NEW.event_id IS DISTINCT FROM OLD.event_id OR NEW.created_by IS DISTINCT FROM OLD.created_by) THEN
        RAISE EXCEPTION 'Нельзя менять ключ или автора события';
    END IF;
    RETURN NEW;
END;
$$;
DROP TRIGGER IF EXISTS guard_event_update_before_update ON public.events;
CREATE TRIGGER guard_event_update_before_update
    BEFORE UPDATE ON public.events
    FOR EACH ROW EXECUTE FUNCTION public.guard_event_update();
DROP POLICY IF EXISTS "Public can read birthdays" ON public.birthdays;
CREATE POLICY "Public can read birthdays"
    ON public.birthdays FOR SELECT TO anon, authenticated USING (true);
DROP POLICY IF EXISTS "Admins manage birthdays" ON public.birthdays;
CREATE POLICY "Admins manage birthdays"
    ON public.birthdays FOR ALL TO authenticated
    USING (public.is_buhlo_admin()) WITH CHECK (public.is_buhlo_admin());

DROP POLICY IF EXISTS "Public can read holidays" ON public.holidays;
CREATE POLICY "Public can read holidays"
    ON public.holidays FOR SELECT TO anon, authenticated USING (true);
DROP POLICY IF EXISTS "Admins manage holidays" ON public.holidays;
CREATE POLICY "Admins manage holidays"
    ON public.holidays FOR ALL TO authenticated
    USING (public.is_buhlo_admin()) WITH CHECK (public.is_buhlo_admin());
DROP POLICY IF EXISTS "Members add holidays" ON public.holidays;
CREATE POLICY "Members add holidays"
    ON public.holidays FOR INSERT TO authenticated
    WITH CHECK (
        (SELECT auth.uid()) IS NOT NULL
        AND length(btrim(name)) BETWEEN 1 AND 120
        AND event_type IN ('general', 'moto')
    );

DROP POLICY IF EXISTS "Admins read registrations" ON public.event_registrations;
CREATE POLICY "Admins read registrations"
    ON public.event_registrations FOR SELECT TO authenticated
    USING (public.is_buhlo_admin());
DROP POLICY IF EXISTS "Admins manage registrations" ON public.event_registrations;
CREATE POLICY "Admins manage registrations"
    ON public.event_registrations FOR ALL TO authenticated
    USING (public.is_buhlo_admin()) WITH CHECK (public.is_buhlo_admin());

DROP FUNCTION IF EXISTS public.get_public_event_participants();

CREATE FUNCTION public.get_public_event_participants()
RETURNS TABLE (event_id bigint, name text, notes text)
LANGUAGE sql
STABLE
SECURITY DEFINER
SET search_path = ''
AS $$
    SELECT registrations.event_id, registrations.name, registrations.notes
    FROM public.event_registrations AS registrations
    ORDER BY registrations.registered_at, registrations.id;
$$;

CREATE OR REPLACE FUNCTION public.submit_event_registration(
    p_event_id bigint,
    p_registration_key uuid,
    p_name text,
    p_contact text DEFAULT 'не указан',
    p_notes text DEFAULT ''
)
RETURNS TABLE (registration_id bigint, event_id bigint, name text)
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = ''
AS $$
DECLARE
    event_limit integer;
    current_count bigint;
    account_name text;
    saved_registration public.event_registrations%ROWTYPE;
BEGIN
    IF auth.uid() IS NULL THEN
        RAISE EXCEPTION 'Для записи необходимо войти в аккаунт' USING ERRCODE = '42501';
    END IF;

    SELECT nullif(btrim(profiles.username), '')
    INTO account_name
    FROM public.user_profiles AS profiles
    WHERE profiles.id = auth.uid();

    IF account_name IS NULL THEN
        RAISE EXCEPTION 'В профиле аккаунта не указано имя';
    END IF;

    IF p_registration_key IS NULL
       OR length(account_name) > 120
       OR length(coalesce(p_contact, '')) > 200
       OR length(coalesce(p_notes, '')) > 2000 THEN
        RAISE EXCEPTION 'Некорректные данные регистрации';
    END IF;

    SELECT coalesce(events."maxParticipants", 50)
    INTO event_limit
    FROM public.events AS events
    WHERE events.event_id = p_event_id
    FOR UPDATE;

    IF NOT FOUND THEN
        RAISE EXCEPTION 'Событие не найдено';
    END IF;

    SELECT count(*)
    INTO current_count
    FROM public.event_registrations AS registrations
    WHERE registrations.event_id = p_event_id;

    SELECT *
    INTO saved_registration
    FROM public.event_registrations AS registrations
    WHERE registrations.event_id = p_event_id
      AND registrations.registration_key = p_registration_key;

    IF FOUND THEN
        RETURN QUERY SELECT saved_registration.id, saved_registration.event_id, saved_registration.name;
        RETURN;
    END IF;

    IF current_count >= event_limit THEN
        RAISE EXCEPTION 'Мест на событие больше нет';
    END IF;

    INSERT INTO public.event_registrations (event_id, registration_key, name, contact, notes)
    VALUES (
        p_event_id,
        p_registration_key,
        account_name,
        coalesce(nullif(trim(p_contact), ''), 'не указан'),
        coalesce(trim(p_notes), '')
    )
    RETURNING * INTO saved_registration;

    RETURN QUERY SELECT saved_registration.id, saved_registration.event_id, saved_registration.name;
END;
$$;

CREATE OR REPLACE FUNCTION public.replace_events(p_events jsonb)
RETURNS void
LANGUAGE plpgsql
SET search_path = ''
AS $$
BEGIN
    IF NOT public.is_buhlo_admin() OR p_events IS NULL OR jsonb_typeof(p_events) <> 'array' THEN
        RAISE EXCEPTION 'Недостаточно прав или неверный список событий';
    END IF;

    INSERT INTO public.events (
        event_id, title, date, time, location, description, recurrence, "maxParticipants"
    )
    SELECT
        item.event_id, item.title, item.date, nullif(item.time, ''),
        coalesce(item.location, ''), item.description, item.recurrence,
        coalesce(item."maxParticipants", 50)
    FROM jsonb_to_recordset(p_events) AS item(
        event_id bigint,
        title text,
        date date,
        time text,
        location text,
        description text,
        recurrence text,
        "maxParticipants" integer
    )
    ON CONFLICT (event_id) DO UPDATE SET
        title = EXCLUDED.title,
        date = EXCLUDED.date,
        time = EXCLUDED.time,
        location = EXCLUDED.location,
        description = EXCLUDED.description,
        recurrence = EXCLUDED.recurrence,
        "maxParticipants" = EXCLUDED."maxParticipants";

    DELETE FROM public.events AS events
    WHERE NOT EXISTS (
        SELECT 1
        FROM jsonb_to_recordset(p_events) AS item(event_id bigint)
        WHERE item.event_id = events.event_id
    );

    INSERT INTO public.event_registrations (
        event_id, registration_key, name, contact, notes, registered_at
    )
    SELECT
        item.event_id,
        gen_random_uuid(),
        trim(imported.person->>'name'),
        coalesce(nullif(trim(imported.person->>'contact'), ''), 'не указан'),
        coalesce(imported.person->>'notes', ''),
        coalesce(nullif(imported.person->>'registeredAt', '')::timestamptz, now())
    FROM jsonb_to_recordset(p_events) AS item(event_id bigint, participants jsonb)
    CROSS JOIN LATERAL jsonb_array_elements(
        CASE
            WHEN jsonb_typeof(item.participants) = 'array' THEN item.participants
            ELSE '[]'::jsonb
        END
    ) AS imported(person)
    WHERE jsonb_typeof(imported.person) = 'object'
      AND length(trim(coalesce(imported.person->>'name', ''))) BETWEEN 1 AND 120
      AND NOT EXISTS (
          SELECT 1 FROM public.event_registrations AS existing
          WHERE existing.event_id = item.event_id
      );

    IF pg_get_serial_sequence('public.events', 'event_id') IS NOT NULL THEN
        PERFORM setval(
            pg_get_serial_sequence('public.events', 'event_id'),
            coalesce((SELECT max(event_id) FROM public.events), 1),
            EXISTS (SELECT 1 FROM public.events)
        );
    END IF;
END;
$$;

CREATE OR REPLACE FUNCTION public.replace_birthdays(p_birthdays jsonb)
RETURNS void
LANGUAGE plpgsql
SET search_path = ''
AS $$
BEGIN
    IF NOT public.is_buhlo_admin() OR p_birthdays IS NULL OR jsonb_typeof(p_birthdays) <> 'array' THEN
        RAISE EXCEPTION 'Недостаточно прав или неверный список дней рождения';
    END IF;

    DELETE FROM public.birthdays WHERE true;
    INSERT INTO public.birthdays (date, name)
    SELECT item.date, item.name
    FROM jsonb_to_recordset(p_birthdays) AS item(date date, name text);
END;
$$;

CREATE OR REPLACE FUNCTION public.replace_holidays(p_holidays jsonb)
RETURNS void
LANGUAGE plpgsql
SET search_path = ''
AS $$
BEGIN
    IF NOT public.is_buhlo_admin() OR p_holidays IS NULL OR jsonb_typeof(p_holidays) <> 'array' THEN
        RAISE EXCEPTION 'Недостаточно прав или неверный список праздников';
    END IF;

    DELETE FROM public.holidays WHERE true;
    INSERT INTO public.holidays (date, name, event_type)
    SELECT item.date, item.name, coalesce(item.event_type, 'general')
    FROM jsonb_to_recordset(p_holidays) AS item(date text, name text, event_type text);
END;
$$;

REVOKE ALL ON FUNCTION public.get_public_event_participants() FROM PUBLIC;
REVOKE ALL ON FUNCTION public.submit_event_registration(bigint, uuid, text, text, text) FROM PUBLIC;
CREATE OR REPLACE FUNCTION public.check_event_registration(p_event_id bigint, p_registration_key uuid)
RETURNS boolean
LANGUAGE sql
STABLE
SECURITY DEFINER
SET search_path = ''
AS $$
    SELECT EXISTS (
        SELECT 1
        FROM public.event_registrations AS registrations
        WHERE registrations.event_id = p_event_id
          AND registrations.registration_key = p_registration_key
    );
$$;

REVOKE ALL ON FUNCTION public.check_event_registration(bigint, uuid) FROM PUBLIC;
GRANT EXECUTE ON FUNCTION public.check_event_registration(bigint, uuid) TO anon, authenticated;
REVOKE ALL ON FUNCTION public.replace_events(jsonb) FROM PUBLIC;
REVOKE ALL ON FUNCTION public.replace_birthdays(jsonb) FROM PUBLIC;
REVOKE ALL ON FUNCTION public.replace_holidays(jsonb) FROM PUBLIC;
GRANT EXECUTE ON FUNCTION public.get_public_event_participants() TO anon, authenticated;
GRANT EXECUTE ON FUNCTION public.submit_event_registration(bigint, uuid, text, text, text) TO anon, authenticated;
GRANT EXECUTE ON FUNCTION public.replace_events(jsonb) TO authenticated;
GRANT EXECUTE ON FUNCTION public.replace_birthdays(jsonb) TO authenticated;
GRANT EXECUTE ON FUNCTION public.replace_holidays(jsonb) TO authenticated;

DO $$
DECLARE
    sequence_name text := pg_get_serial_sequence('public.events', 'event_id');
BEGIN
    IF sequence_name IS NOT NULL THEN
        PERFORM setval(
            sequence_name,
            coalesce((SELECT max(event_id) FROM public.events), 1),
            EXISTS (SELECT 1 FROM public.events)
        );
    END IF;
END
$$;

NOTIFY pgrst, 'reload schema';

-- Backups: private Storage bucket BHCH_DATA (data/events.json, birthdays.json, holidays.json).
-- Only admins can read and write; the bucket stays non-public.
INSERT INTO storage.buckets (id, name, public)
VALUES ('BHCH_DATA', 'BHCH_DATA', false)
ON CONFLICT (id) DO NOTHING;

-- Size limit is enforced by the bucket (Storage RLS cannot see file metadata on insert).
-- No MIME restriction here: the bucket also stores JSON backups.
UPDATE storage.buckets SET file_size_limit = 10485760 WHERE id = 'BHCH_DATA';

DROP POLICY IF EXISTS "Admins read BHCH_DATA" ON storage.objects;
CREATE POLICY "Admins read BHCH_DATA"
    ON storage.objects FOR SELECT TO authenticated
    USING (bucket_id = 'BHCH_DATA' AND public.is_buhlo_admin());

DROP POLICY IF EXISTS "Admins insert BHCH_DATA" ON storage.objects;
CREATE POLICY "Admins insert BHCH_DATA"
    ON storage.objects FOR INSERT TO authenticated
    WITH CHECK (bucket_id = 'BHCH_DATA' AND public.is_buhlo_admin());

DROP POLICY IF EXISTS "Admins update BHCH_DATA" ON storage.objects;
CREATE POLICY "Admins update BHCH_DATA"
    ON storage.objects FOR UPDATE TO authenticated
    USING (bucket_id = 'BHCH_DATA' AND public.is_buhlo_admin())
    WITH CHECK (bucket_id = 'BHCH_DATA' AND public.is_buhlo_admin());

-- Gallery: photos in BHCH_DATA/gallery are readable by everyone (the site loads them with the anon key).
-- Everything else in the bucket (data/ backups) stays admin-only.
DROP POLICY IF EXISTS "Public read BHCH_DATA gallery" ON storage.objects;
CREATE POLICY "Public read BHCH_DATA gallery"
    ON storage.objects FOR SELECT TO anon, authenticated
    USING (bucket_id = 'BHCH_DATA' AND (storage.foldername(name))[1] = 'gallery');

-- Hub entry questions. Answers are stored only as bcrypt hashes and checked on the server.
CREATE EXTENSION IF NOT EXISTS pgcrypto WITH SCHEMA extensions;

CREATE TABLE IF NOT EXISTS public.hub_questions (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    question text NOT NULL CHECK (length(trim(question)) BETWEEN 1 AND 300),
    answer_hash text NOT NULL,
    description text NOT NULL DEFAULT '' CHECK (length(description) <= 2000),
    available_from date,
    available_to date,
    CHECK (available_from IS NULL OR available_to IS NULL OR available_to >= available_from)
);

ALTER TABLE public.hub_questions ENABLE ROW LEVEL SECURITY;

REVOKE ALL ON public.hub_questions FROM anon, authenticated;
GRANT SELECT (id, question, description, available_from, available_to), DELETE
    ON public.hub_questions TO authenticated;

DROP POLICY IF EXISTS "Admins read hub questions" ON public.hub_questions;
CREATE POLICY "Admins read hub questions"
    ON public.hub_questions FOR SELECT TO authenticated
    USING (public.is_buhlo_admin());

DROP POLICY IF EXISTS "Admins delete hub questions" ON public.hub_questions;
CREATE POLICY "Admins delete hub questions"
    ON public.hub_questions FOR DELETE TO authenticated
    USING (public.is_buhlo_admin());

CREATE OR REPLACE FUNCTION public.get_hub_question()
RETURNS TABLE (id bigint, question text)
LANGUAGE sql
STABLE
SECURITY DEFINER
SET search_path = ''
AS $$
    SELECT questions.id, questions.question
    FROM public.hub_questions AS questions
    WHERE (questions.available_from IS NULL OR questions.available_from <= (now() AT TIME ZONE 'Europe/Moscow')::date)
      AND (questions.available_to IS NULL OR questions.available_to >= (now() AT TIME ZONE 'Europe/Moscow')::date)
    ORDER BY random()
    LIMIT 1;
$$;

CREATE OR REPLACE FUNCTION public.check_hub_answer(p_id bigint, p_answer text)
RETURNS boolean
LANGUAGE sql
STABLE
SECURITY DEFINER
SET search_path = extensions, pg_temp
AS $$
    SELECT coalesce((
        SELECT questions.answer_hash = extensions.crypt(lower(trim(coalesce(p_answer, ''))), questions.answer_hash)
        FROM public.hub_questions AS questions
        WHERE questions.id = p_id
          AND (questions.available_from IS NULL OR questions.available_from <= (now() AT TIME ZONE 'Europe/Moscow')::date)
          AND (questions.available_to IS NULL OR questions.available_to >= (now() AT TIME ZONE 'Europe/Moscow')::date)
    ), false);
$$;

CREATE OR REPLACE FUNCTION public.save_hub_question(
    p_id bigint,
    p_question text,
    p_answer text,
    p_description text,
    p_from date,
    p_to date
)
RETURNS bigint
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = extensions, pg_temp
AS $$
DECLARE
    saved_id bigint;
    has_answer boolean := length(trim(coalesce(p_answer, ''))) > 0;
BEGIN
    IF NOT public.is_buhlo_admin() THEN
        RAISE EXCEPTION 'Недостаточно прав';
    END IF;

    IF p_id IS NULL THEN
        IF NOT has_answer THEN
            RAISE EXCEPTION 'Для нового вопроса нужен правильный ответ';
        END IF;
        INSERT INTO public.hub_questions (question, answer_hash, description, available_from, available_to)
        VALUES (
            trim(p_question),
            extensions.crypt(lower(trim(p_answer)), extensions.gen_salt('bf')),
            coalesce(p_description, ''),
            p_from,
            p_to
        )
        RETURNING id INTO saved_id;
    ELSE
        UPDATE public.hub_questions AS questions
        SET question = trim(p_question),
            answer_hash = CASE WHEN has_answer
                THEN extensions.crypt(lower(trim(p_answer)), extensions.gen_salt('bf'))
                ELSE questions.answer_hash END,
            description = coalesce(p_description, ''),
            available_from = p_from,
            available_to = p_to
        WHERE questions.id = p_id
        RETURNING questions.id INTO saved_id;

        IF saved_id IS NULL THEN
            RAISE EXCEPTION 'Вопрос не найден';
        END IF;
    END IF;

    RETURN saved_id;
END;
$$;

REVOKE ALL ON FUNCTION public.get_hub_question() FROM PUBLIC;
-- Admin user management: list accounts and delete non-admin ones.
CREATE OR REPLACE FUNCTION public.admin_list_users()
RETURNS TABLE (
    id uuid,
    email text,
    username text,
    role text,
    created_at timestamptz,
    email_confirmed boolean,
    last_sign_in_at timestamptz
)
LANGUAGE plpgsql
STABLE
SECURITY DEFINER
SET search_path = ''
AS $$
BEGIN
    IF NOT public.is_buhlo_admin() THEN
        RAISE EXCEPTION 'Недостаточно прав';
    END IF;
    RETURN QUERY
    SELECT u.id, u.email::text, p.username, coalesce(p.role, 'user'), u.created_at,
           u.email_confirmed_at IS NOT NULL, u.last_sign_in_at
    FROM auth.users AS u
    LEFT JOIN public.user_profiles AS p ON p.id = u.id
    ORDER BY u.created_at DESC;
END;
$$;

CREATE OR REPLACE FUNCTION public.admin_delete_user(p_id uuid)
RETURNS void
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = ''
AS $$
BEGIN
    IF NOT public.is_buhlo_admin() THEN
        RAISE EXCEPTION 'Недостаточно прав';
    END IF;
    IF p_id = (SELECT auth.uid()) THEN
        RAISE EXCEPTION 'Нельзя удалить самого себя';
    END IF;
    IF EXISTS (
        SELECT 1 FROM auth.users
        WHERE id = p_id AND raw_app_meta_data ->> 'role' = 'admin'
    ) THEN
        RAISE EXCEPTION 'Нельзя удалить администратора';
    END IF;
    DELETE FROM auth.users WHERE id = p_id;
    IF NOT FOUND THEN
        RAISE EXCEPTION 'Пользователь не найден';
    END IF;
END;
$$;

CREATE OR REPLACE FUNCTION public.admin_rename_user(p_id uuid, p_username text)
RETURNS void
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = ''
AS $$
DECLARE
    new_name text := btrim(coalesce(p_username, ''));
BEGIN
    IF NOT public.is_buhlo_admin() THEN
        RAISE EXCEPTION 'Недостаточно прав';
    END IF;
    IF char_length(new_name) NOT BETWEEN 2 AND 40 THEN
        RAISE EXCEPTION 'Имя — от 2 до 40 символов';
    END IF;
    IF EXISTS (SELECT 1 FROM public.user_profiles WHERE username = new_name AND id <> p_id) THEN
        RAISE EXCEPTION 'Такое имя уже занято';
    END IF;
    UPDATE public.user_profiles SET username = new_name WHERE id = p_id;
    IF NOT FOUND THEN
        RAISE EXCEPTION 'Пользователь не найден';
    END IF;
END;
$$;

REVOKE ALL ON FUNCTION public.admin_rename_user(uuid, text) FROM PUBLIC, anon;
GRANT EXECUTE ON FUNCTION public.admin_rename_user(uuid, text) TO authenticated;

REVOKE ALL ON FUNCTION public.admin_list_users() FROM PUBLIC, anon;
REVOKE ALL ON FUNCTION public.admin_delete_user(uuid) FROM PUBLIC, anon;
GRANT EXECUTE ON FUNCTION public.admin_list_users() TO authenticated;
GRANT EXECUTE ON FUNCTION public.admin_delete_user(uuid) TO authenticated;

-- Registration gate: a one-time ticket is issued only for a correct hub answer, and a
-- trigger on auth.users refuses sign-ups without a valid ticket (so the Auth API cannot be
-- called directly to bypass the question). Tickets live 15 minutes; only hashes are stored.
CREATE TABLE IF NOT EXISTS public.signup_tickets (
    token_hash text PRIMARY KEY,
    expires_at timestamptz NOT NULL DEFAULT now() + interval '15 minutes'
);
ALTER TABLE public.signup_tickets ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON public.signup_tickets FROM PUBLIC, anon, authenticated;

CREATE OR REPLACE FUNCTION public.issue_signup_ticket(p_id bigint, p_answer text)
RETURNS text
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = extensions, pg_temp
AS $$
DECLARE
    new_token text;
BEGIN
    IF NOT public.check_hub_answer(p_id, p_answer) THEN
        RETURN NULL;
    END IF;
    DELETE FROM public.signup_tickets WHERE expires_at < now();
    new_token := encode(extensions.gen_random_bytes(24), 'hex');
    INSERT INTO public.signup_tickets (token_hash)
    VALUES (encode(extensions.digest(new_token, 'sha256'), 'hex'));
    RETURN new_token;
END;
$$;

CREATE OR REPLACE FUNCTION public.require_signup_ticket()
RETURNS trigger
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = extensions, pg_temp
AS $$
DECLARE
    used_count integer;
BEGIN
    DELETE FROM public.signup_tickets
    WHERE token_hash = encode(extensions.digest(coalesce(NEW.raw_user_meta_data ->> 'signup_ticket', ''), 'sha256'), 'hex')
      AND expires_at >= now();
    GET DIAGNOSTICS used_count = ROW_COUNT;
    IF used_count = 0 THEN
        RAISE EXCEPTION 'Регистрация доступна только после верного ответа на контрольный вопрос';
    END IF;
    NEW.raw_user_meta_data := NEW.raw_user_meta_data - 'signup_ticket';
    RETURN NEW;
END;
$$;

REVOKE ALL ON FUNCTION public.issue_signup_ticket(bigint, text) FROM PUBLIC;
GRANT EXECUTE ON FUNCTION public.issue_signup_ticket(bigint, text) TO anon, authenticated;
REVOKE ALL ON FUNCTION public.require_signup_ticket() FROM PUBLIC, anon, authenticated;
DROP TRIGGER IF EXISTS require_signup_ticket_before_insert ON auth.users;
CREATE TRIGGER require_signup_ticket_before_insert
    BEFORE INSERT ON auth.users
    FOR EACH ROW EXECUTE FUNCTION public.require_signup_ticket();

REVOKE ALL ON FUNCTION public.check_hub_answer(bigint, text) FROM PUBLIC;
REVOKE ALL ON FUNCTION public.save_hub_question(bigint, text, text, text, date, date) FROM PUBLIC;
GRANT EXECUTE ON FUNCTION public.get_hub_question() TO anon, authenticated;
GRANT EXECUTE ON FUNCTION public.check_hub_answer(bigint, text) TO anon, authenticated;
GRANT EXECUTE ON FUNCTION public.save_hub_question(bigint, text, text, text, date, date) TO authenticated;

CREATE OR REPLACE FUNCTION public.delete_hub_question(p_id bigint)
RETURNS boolean
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = ''
AS $$
DECLARE
    deleted_count integer;
BEGIN
    IF NOT public.is_buhlo_admin() THEN
        RAISE EXCEPTION 'Недостаточно прав';
    END IF;
    DELETE FROM public.hub_questions WHERE id = p_id;
    GET DIAGNOSTICS deleted_count = ROW_COUNT;
    RETURN deleted_count > 0;
END;
$$;

REVOKE ALL ON FUNCTION public.delete_hub_question(bigint) FROM PUBLIC;
GRANT EXECUTE ON FUNCTION public.delete_hub_question(bigint) TO authenticated;
GRANT SELECT (id, question, description, available_from, available_to) ON public.hub_questions TO authenticated;
NOTIFY pgrst, 'reload schema';

-- Gallery: categories and photos. Files live in the Storage bucket BHCH_DATA under
-- gallery/<category_id>/ (full image) and gallery/<category_id>/thumbs/ (preview).
CREATE TABLE IF NOT EXISTS public.gallery_categories (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name text NOT NULL UNIQUE CHECK (length(trim(name)) BETWEEN 1 AND 60)
);

CREATE TABLE IF NOT EXISTS public.gallery_photos (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    category_id bigint NOT NULL REFERENCES public.gallery_categories(id) ON DELETE CASCADE,
    path text NOT NULL UNIQUE,
    thumb_path text,
    caption text NOT NULL DEFAULT '' CHECK (length(caption) <= 200),
    created_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS gallery_photos_category_idx ON public.gallery_photos (category_id);

ALTER TABLE public.gallery_categories ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.gallery_photos ENABLE ROW LEVEL SECURITY;

GRANT SELECT ON public.gallery_categories, public.gallery_photos TO anon, authenticated;
GRANT INSERT, UPDATE, DELETE ON public.gallery_categories, public.gallery_photos TO authenticated;

DROP POLICY IF EXISTS "Public can read gallery categories" ON public.gallery_categories;
CREATE POLICY "Public can read gallery categories"
    ON public.gallery_categories FOR SELECT TO anon, authenticated USING (true);
DROP POLICY IF EXISTS "Admins manage gallery categories" ON public.gallery_categories;
CREATE POLICY "Admins manage gallery categories"
    ON public.gallery_categories FOR ALL TO authenticated
    USING (public.is_buhlo_admin()) WITH CHECK (public.is_buhlo_admin());
DROP POLICY IF EXISTS "Members add gallery categories" ON public.gallery_categories;
CREATE POLICY "Members add gallery categories"
    ON public.gallery_categories FOR INSERT TO authenticated
    WITH CHECK ((SELECT auth.uid()) IS NOT NULL);

DROP POLICY IF EXISTS "Public can read gallery photos" ON public.gallery_photos;
CREATE POLICY "Public can read gallery photos"
    ON public.gallery_photos FOR SELECT TO anon, authenticated USING (true);
DROP POLICY IF EXISTS "Admins manage gallery photos" ON public.gallery_photos;
CREATE POLICY "Admins manage gallery photos"
    ON public.gallery_photos FOR ALL TO authenticated
    USING (public.is_buhlo_admin()) WITH CHECK (public.is_buhlo_admin());
DROP POLICY IF EXISTS "Members add gallery photos" ON public.gallery_photos;
CREATE POLICY "Members add gallery photos"
    ON public.gallery_photos FOR INSERT TO authenticated
    WITH CHECK (
        (SELECT auth.uid()) IS NOT NULL
        AND EXISTS (
            SELECT 1
            FROM storage.objects AS image
            WHERE image.bucket_id = 'BHCH_DATA'
              AND image.name = path
              AND image.owner_id = (SELECT auth.uid())::text
        )
        AND (
            thumb_path IS NULL
            OR EXISTS (
                SELECT 1
                FROM storage.objects AS thumbnail
                WHERE thumbnail.bucket_id = 'BHCH_DATA'
                  AND thumbnail.name = thumb_path
                  AND thumbnail.owner_id = (SELECT auth.uid())::text
            )
        )
    );

-- "🍉Инфо от Арбузика🍉": posts with optional link and images. Only the info editor (a single
-- designated administrator) may add/edit; any administrator may delete.
CREATE OR REPLACE FUNCTION public.is_info_editor()
RETURNS boolean
LANGUAGE sql
STABLE
AS $$
    SELECT public.is_buhlo_admin()
        AND lower(coalesce(auth.jwt() ->> 'email', '')) = 'ssdavidchuk@gmail.com';
$$;
REVOKE ALL ON FUNCTION public.is_info_editor() FROM PUBLIC;
GRANT EXECUTE ON FUNCTION public.is_info_editor() TO anon, authenticated;

CREATE TABLE IF NOT EXISTS public.info_posts (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title text NOT NULL CHECK (length(btrim(title)) BETWEEN 1 AND 200),
    body text NOT NULL DEFAULT '' CHECK (length(body) <= 5000),
    link_url text CHECK (link_url IS NULL OR (length(link_url) <= 500 AND link_url ~* '^https?://')),
    created_at timestamptz NOT NULL DEFAULT now()
);

ALTER TABLE public.gallery_photos
    ADD COLUMN IF NOT EXISTS info_post_id bigint REFERENCES public.info_posts (id) ON DELETE CASCADE;
CREATE INDEX IF NOT EXISTS gallery_photos_info_post_idx ON public.gallery_photos (info_post_id);

ALTER TABLE public.info_posts ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON public.info_posts FROM anon, authenticated;
GRANT SELECT ON public.info_posts TO anon, authenticated;
GRANT INSERT, UPDATE, DELETE ON public.info_posts TO authenticated;

DROP POLICY IF EXISTS "Public can read info posts" ON public.info_posts;
CREATE POLICY "Public can read info posts"
    ON public.info_posts FOR SELECT TO anon, authenticated USING (true);
DROP POLICY IF EXISTS "Info editor adds info posts" ON public.info_posts;
CREATE POLICY "Info editor adds info posts"
    ON public.info_posts FOR INSERT TO authenticated WITH CHECK (public.is_info_editor());
DROP POLICY IF EXISTS "Info editor edits info posts" ON public.info_posts;
CREATE POLICY "Info editor edits info posts"
    ON public.info_posts FOR UPDATE TO authenticated
    USING (public.is_info_editor()) WITH CHECK (public.is_info_editor());
DROP POLICY IF EXISTS "Admins delete info posts" ON public.info_posts;
CREATE POLICY "Admins delete info posts"
    ON public.info_posts FOR DELETE TO authenticated USING (public.is_buhlo_admin());

-- Likes (🍾) for info posts: only signed-in members/admins can like; names are readable
-- by everyone through get_info_likes() (profiles themselves stay private).
CREATE TABLE IF NOT EXISTS public.info_post_likes (
    post_id bigint NOT NULL REFERENCES public.info_posts (id) ON DELETE CASCADE,
    user_id uuid NOT NULL REFERENCES auth.users (id) ON DELETE CASCADE,
    created_at timestamptz NOT NULL DEFAULT now(),
    PRIMARY KEY (post_id, user_id)
);

ALTER TABLE public.info_post_likes ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON public.info_post_likes FROM anon, authenticated;
GRANT SELECT, INSERT, DELETE ON public.info_post_likes TO authenticated;

DROP POLICY IF EXISTS "Users read own info likes" ON public.info_post_likes;
CREATE POLICY "Users read own info likes"
    ON public.info_post_likes FOR SELECT TO authenticated
    USING (user_id = (SELECT auth.uid()));
DROP POLICY IF EXISTS "Users add own info likes" ON public.info_post_likes;
CREATE POLICY "Users add own info likes"
    ON public.info_post_likes FOR INSERT TO authenticated
    WITH CHECK (user_id = (SELECT auth.uid()));
DROP POLICY IF EXISTS "Users remove own info likes" ON public.info_post_likes;
CREATE POLICY "Users remove own info likes"
    ON public.info_post_likes FOR DELETE TO authenticated
    USING (user_id = (SELECT auth.uid()));

CREATE OR REPLACE FUNCTION public.get_info_likes()
RETURNS TABLE (post_id bigint, user_id uuid, username text, created_at timestamptz)
LANGUAGE sql
STABLE
SECURITY DEFINER
SET search_path = ''
AS $$
    SELECT likes.post_id, likes.user_id,
           coalesce(nullif(btrim(profiles.username), ''), 'Участник'),
           likes.created_at
    FROM public.info_post_likes AS likes
    LEFT JOIN public.user_profiles AS profiles ON profiles.id = likes.user_id
    ORDER BY likes.created_at;
$$;
REVOKE ALL ON FUNCTION public.get_info_likes() FROM PUBLIC;
GRANT EXECUTE ON FUNCTION public.get_info_likes() TO anon, authenticated;
-- Rename the legacy category (kept so existing photos stay linked).
UPDATE public.gallery_categories SET name = '🍉Инфо от Арбузика🍉'
WHERE name = 'Инфо от Сергеича'
  AND NOT EXISTS (SELECT 1 FROM public.gallery_categories WHERE name = '🍉Инфо от Арбузика🍉');

INSERT INTO public.gallery_categories (name)
VALUES ('🍉Инфо от Арбузика🍉')
ON CONFLICT (name) DO NOTHING;

-- Writing into the info category is restricted to the info editor (restrictive policies
-- apply on top of the existing permissive ones, including the general admin policy).
CREATE OR REPLACE FUNCTION public.info_category_id()
RETURNS bigint
LANGUAGE sql
STABLE
SECURITY DEFINER
SET search_path = ''
AS $$
    SELECT id FROM public.gallery_categories WHERE name = '🍉Инфо от Арбузика🍉';
$$;
REVOKE ALL ON FUNCTION public.info_category_id() FROM PUBLIC;
GRANT EXECUTE ON FUNCTION public.info_category_id() TO anon, authenticated;

DROP POLICY IF EXISTS "Only info editor adds info photos" ON public.gallery_photos;
CREATE POLICY "Only info editor adds info photos"
    ON public.gallery_photos AS RESTRICTIVE FOR INSERT TO authenticated
    WITH CHECK (
        (category_id IS DISTINCT FROM public.info_category_id() AND info_post_id IS NULL)
        OR public.is_info_editor()
    );

DROP POLICY IF EXISTS "Only info editor uploads info files" ON storage.objects;
CREATE POLICY "Only info editor uploads info files"
    ON storage.objects AS RESTRICTIVE FOR INSERT TO authenticated
    WITH CHECK (
        bucket_id <> 'BHCH_DATA'
        OR (storage.foldername(name))[1] IS DISTINCT FROM 'gallery'
        OR (storage.foldername(name))[2] IS DISTINCT FROM public.info_category_id()::text
        OR public.is_info_editor()
    );

NOTIFY pgrst, 'reload schema';
DROP POLICY IF EXISTS "Members upload gallery images" ON storage.objects;
CREATE POLICY "Members upload gallery images"
    ON storage.objects FOR INSERT TO authenticated
    WITH CHECK (
        bucket_id = 'BHCH_DATA'
        AND (storage.foldername(name))[1] = 'gallery'
        AND CASE
            WHEN coalesce((storage.foldername(name))[2], '') ~ '^[0-9]+$'
                THEN EXISTS (
                    SELECT 1
                    FROM public.gallery_categories AS category
                    WHERE category.id = ((storage.foldername(storage.objects.name))[2])::bigint
                )
            ELSE false
        END
    );

DROP POLICY IF EXISTS "Users remove unlisted gallery uploads" ON storage.objects;
CREATE POLICY "Users remove unlisted gallery uploads"
    ON storage.objects FOR DELETE TO authenticated
    USING (
        bucket_id = 'BHCH_DATA'
        AND (storage.foldername(name))[1] = 'gallery'
        AND owner_id = (SELECT auth.uid())::text
        AND NOT EXISTS (
            SELECT 1
            FROM public.gallery_photos AS photo
            WHERE photo.path = storage.objects.name
               OR photo.thumb_path = storage.objects.name
        )
    );

-- Admins may also remove files from the bucket (gallery photos and backups).
DROP POLICY IF EXISTS "Admins delete BHCH_DATA" ON storage.objects;
CREATE POLICY "Admins delete BHCH_DATA"
    ON storage.objects FOR DELETE TO authenticated
    USING (bucket_id = 'BHCH_DATA' AND public.is_buhlo_admin());

-- Site visit statistics (no direct table access; only via RPC).
CREATE TABLE IF NOT EXISTS public.site_visits (
    id bigint GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    visited_at timestamptz NOT NULL DEFAULT now(),
    visitor_id uuid NOT NULL,
    page text NOT NULL DEFAULT 'hub' CHECK (char_length(page) <= 60)
);
CREATE INDEX IF NOT EXISTS site_visits_visited_at_idx ON public.site_visits (visited_at);
ALTER TABLE public.site_visits ENABLE ROW LEVEL SECURITY;

-- No direct access: visits are written and read only through the RPC functions below.
DROP POLICY IF EXISTS "No direct access to site_visits" ON public.site_visits;
CREATE POLICY "No direct access to site_visits"
    ON public.site_visits FOR ALL TO anon, authenticated
    USING (false) WITH CHECK (false);

CREATE OR REPLACE FUNCTION public.log_site_visit(p_visitor_id uuid, p_page text DEFAULT 'hub')
RETURNS void
LANGUAGE plpgsql SECURITY DEFINER SET search_path = public
AS $$
DECLARE
    v_page text := left(coalesce(nullif(trim(p_page), ''), 'hub'), 60);
BEGIN
    IF p_visitor_id IS NULL THEN RETURN; END IF;
    IF EXISTS (
        SELECT 1 FROM public.site_visits
        WHERE visitor_id = p_visitor_id AND page = v_page
          AND visited_at > now() - interval '30 minutes'
    ) THEN RETURN; END IF;
    INSERT INTO public.site_visits (visitor_id, page) VALUES (p_visitor_id, v_page);
    DELETE FROM public.site_visits WHERE visited_at < now() - interval '400 days';
END;
$$;

CREATE OR REPLACE FUNCTION public.get_visit_stats(p_days integer DEFAULT 30)
RETURNS jsonb
LANGUAGE plpgsql SECURITY DEFINER SET search_path = public
AS $$
DECLARE
    v_days integer := least(greatest(coalesce(p_days, 30), 1), 365);
    v_today date := (now() AT TIME ZONE 'Europe/Moscow')::date;
    v_result jsonb;
BEGIN
    IF NOT public.is_buhlo_admin() THEN
        RAISE EXCEPTION 'forbidden' USING ERRCODE = '42501';
    END IF;

    WITH v AS (
        SELECT (visited_at AT TIME ZONE 'Europe/Moscow')::date AS d, visitor_id
        FROM public.site_visits
        WHERE visited_at >= (v_today - (v_days - 1))::timestamp AT TIME ZONE 'Europe/Moscow'
    ),
    daily AS (
        SELECT g::date AS d,
               count(v.visitor_id) AS visits,
               count(DISTINCT v.visitor_id) AS uniques
        FROM generate_series(v_today - (v_days - 1), v_today, interval '1 day') g
        LEFT JOIN v ON v.d = g::date
        GROUP BY g ORDER BY g
    )
    SELECT jsonb_build_object(
        'today_visits', (SELECT count(*) FROM v WHERE d = v_today),
        'today_unique', (SELECT count(DISTINCT visitor_id) FROM v WHERE d = v_today),
        'week_visits', (SELECT count(*) FROM v WHERE d > v_today - 7),
        'week_unique', (SELECT count(DISTINCT visitor_id) FROM v WHERE d > v_today - 7),
        'month_visits', (SELECT count(*) FROM v WHERE d > v_today - 30),
        'month_unique', (SELECT count(DISTINCT visitor_id) FROM v WHERE d > v_today - 30),
        'daily', (SELECT coalesce(jsonb_agg(jsonb_build_object('date', d, 'visits', visits, 'uniques', uniques) ORDER BY d), '[]'::jsonb) FROM daily)
    ) INTO v_result;
    RETURN v_result;
END;
$$;

CREATE OR REPLACE FUNCTION public.get_storage_stats()
RETURNS jsonb
LANGUAGE plpgsql SECURITY DEFINER SET search_path = public, storage
AS $$
DECLARE
    v_result jsonb;
BEGIN
    IF NOT public.is_buhlo_admin() THEN
        RAISE EXCEPTION 'forbidden' USING ERRCODE = '42501';
    END IF;

    SELECT jsonb_build_object(
        'total_bytes', coalesce(sum(bytes), 0),
        'total_files', coalesce(sum(files), 0),
        'folders', coalesce(jsonb_agg(jsonb_build_object('folder', folder, 'files', files, 'bytes', bytes) ORDER BY bytes DESC), '[]'::jsonb)
    ) INTO v_result
    FROM (
        SELECT folder, count(*) AS files, sum(size) AS bytes
        FROM (
            SELECT coalesce((storage.foldername(name))[1], '(корень)') AS folder,
                   coalesce((metadata->>'size')::bigint, 0) AS size
            FROM storage.objects
            WHERE bucket_id = 'BHCH_DATA'
        ) o GROUP BY folder
    ) f;
    RETURN v_result;
END;
$$;

REVOKE ALL ON FUNCTION public.log_site_visit(uuid, text) FROM PUBLIC;
REVOKE ALL ON FUNCTION public.get_visit_stats(integer) FROM PUBLIC;
REVOKE ALL ON FUNCTION public.get_storage_stats() FROM PUBLIC;
GRANT EXECUTE ON FUNCTION public.log_site_visit(uuid, text) TO anon, authenticated;
GRANT EXECUTE ON FUNCTION public.get_visit_stats(integer) TO authenticated;
GRANT EXECUTE ON FUNCTION public.get_storage_stats() TO authenticated;

NOTIFY pgrst, 'reload schema';
