-- Run this once in the Supabase SQL Editor.
-- Create an Auth user for each administrator, then set app_metadata.role = "admin".

-- events.id stays an independent autoincrement key with no foreign links.
-- events.event_id is the application's event key; registrations reference it.
ALTER TABLE public.events
    ADD COLUMN IF NOT EXISTS time text,
    ADD COLUMN IF NOT EXISTS recurrence text,
    ADD COLUMN IF NOT EXISTS "maxParticipants" integer NOT NULL DEFAULT 50,
    ADD COLUMN IF NOT EXISTS event_id bigint;

UPDATE public.events SET event_id = id WHERE event_id IS NULL;

ALTER TABLE public.events
    ALTER COLUMN event_id SET NOT NULL,
    ALTER COLUMN recurrence DROP NOT NULL,
    ALTER COLUMN created_at SET DEFAULT now();

DO $$
DECLARE
    target_column text;
    sequence_name text;
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM pg_constraint
        WHERE conname = 'events_event_id_key'
          AND conrelid = 'public.events'::regclass
    ) THEN
        ALTER TABLE public.events
            ADD CONSTRAINT events_event_id_key UNIQUE (event_id);
    END IF;

    FOREACH target_column IN ARRAY ARRAY['id', 'event_id'] LOOP
        IF NOT EXISTS (
            SELECT 1
            FROM information_schema.columns AS columns
            WHERE columns.table_schema = 'public'
              AND columns.table_name = 'events'
              AND columns.column_name = target_column
              AND (columns.is_identity = 'YES' OR columns.column_default IS NOT NULL)
        ) THEN
            EXECUTE format(
                'ALTER TABLE public.events ALTER COLUMN %I ADD GENERATED BY DEFAULT AS IDENTITY',
                target_column
            );
        END IF;

        sequence_name := pg_get_serial_sequence('public.events', target_column);
        IF sequence_name IS NOT NULL THEN
            EXECUTE format(
                'SELECT setval(%L, coalesce((SELECT max(%I) FROM public.events), 1), EXISTS (SELECT 1 FROM public.events))',
                sequence_name, target_column
            );
        END IF;
    END LOOP;

    IF NOT EXISTS (
        SELECT 1 FROM pg_constraint
        WHERE conname = 'events_recurrence_check'
          AND conrelid = 'public.events'::regclass
    ) THEN
        ALTER TABLE public.events
            ADD CONSTRAINT events_recurrence_check
            CHECK (recurrence IS NULL OR recurrence = 'yearly');
    END IF;
END
$$;

CREATE TABLE IF NOT EXISTS public.birthdays (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    date date NOT NULL,
    name text NOT NULL CHECK (length(trim(name)) BETWEEN 1 AND 120)
);

CREATE TABLE IF NOT EXISTS public.holidays (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    date text NOT NULL CHECK (
        date ~ '^(0[1-9]|1[0-2])-(0[1-9]|[12][0-9]|3[01])$'
        AND to_char(to_date(date, 'MM-DD'), 'MM-DD') = date
    ),
    name text NOT NULL CHECK (length(trim(name)) BETWEEN 1 AND 120),
    event_type text NOT NULL DEFAULT 'general'
        CHECK (event_type IN ('general', 'moto'))
);

CREATE TABLE IF NOT EXISTS public.event_registrations (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    event_id bigint NOT NULL
        REFERENCES public.events(event_id) ON DELETE CASCADE,
    registration_key uuid NOT NULL,
    name text NOT NULL CHECK (length(trim(name)) BETWEEN 1 AND 120),
    contact text NOT NULL DEFAULT 'не указан' CHECK (length(contact) <= 200),
    notes text NOT NULL DEFAULT '' CHECK (length(notes) <= 2000),
    registered_at timestamptz NOT NULL DEFAULT now(),
    UNIQUE (event_id, registration_key)
);

-- Legacy layout: events.id referenced event_registrations.id, so the old registration
-- id is the event id (events.event_id was filled from events.id above).
ALTER TABLE public.event_registrations
    ADD COLUMN IF NOT EXISTS event_id bigint;

DO $$
DECLARE
    old_fk record;
    legacy_found boolean := false;
    sequence_name text;
BEGIN
    -- Legacy: events.id referenced event_registrations.id (events_id_fkey). Remove it so
    -- events.id has no foreign links and events can be saved without a registration row.
    FOR old_fk IN
        SELECT c.conname, false AS on_id
        FROM pg_constraint AS c
        WHERE c.conrelid = 'public.events'::regclass
          AND c.confrelid = 'public.event_registrations'::regclass
          AND c.contype = 'f'
    LOOP
        EXECUTE format('ALTER TABLE public.events DROP CONSTRAINT %I', old_fk.conname);
        legacy_found := true;
    END LOOP;

    FOR old_fk IN
        SELECT c.conname,
               c.conkey = ARRAY[
                   (SELECT attnum FROM pg_attribute
                    WHERE attrelid = c.conrelid AND attname = 'id' AND NOT attisdropped)
               ]::smallint[] AS on_id
        FROM pg_constraint AS c
        WHERE c.conrelid = 'public.event_registrations'::regclass
          AND c.confrelid = 'public.events'::regclass
          AND c.contype = 'f'
    LOOP
        EXECUTE format('ALTER TABLE public.event_registrations DROP CONSTRAINT %I', old_fk.conname);
        IF old_fk.on_id THEN
            legacy_found := true;
        END IF;
    END LOOP;

    -- In the legacy layout a registration's id equals the id of its event.
    IF legacy_found THEN
        UPDATE public.event_registrations AS registrations
        SET event_id = registrations.id
        WHERE registrations.event_id IS NULL
          AND EXISTS (
              SELECT 1 FROM public.events AS events
              WHERE events.event_id = registrations.id
          );
    END IF;

    IF NOT EXISTS (SELECT 1 FROM public.event_registrations WHERE event_id IS NULL) THEN
        ALTER TABLE public.event_registrations ALTER COLUMN event_id SET NOT NULL;
    END IF;

    IF NOT EXISTS (
        SELECT 1
        FROM information_schema.columns AS columns
        WHERE columns.table_schema = 'public'
          AND columns.table_name = 'event_registrations'
          AND columns.column_name = 'id'
          AND (columns.is_identity = 'YES' OR columns.column_default IS NOT NULL)
    ) THEN
        ALTER TABLE public.event_registrations ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY;
    END IF;

    sequence_name := pg_get_serial_sequence('public.event_registrations', 'id');
    IF sequence_name IS NOT NULL THEN
        PERFORM setval(
            sequence_name,
            coalesce((SELECT max(id) FROM public.event_registrations), 1),
            EXISTS (SELECT 1 FROM public.event_registrations)
        );
    END IF;

    ALTER TABLE public.event_registrations
        ADD CONSTRAINT event_registrations_event_id_fkey
        FOREIGN KEY (event_id) REFERENCES public.events(event_id) ON DELETE CASCADE;
END
$$;

CREATE UNIQUE INDEX IF NOT EXISTS event_registrations_event_key_idx
    ON public.event_registrations (event_id, registration_key);

CREATE INDEX IF NOT EXISTS event_registrations_event_id_idx
    ON public.event_registrations (event_id);

CREATE OR REPLACE FUNCTION public.is_buhlo_admin()
RETURNS boolean
LANGUAGE sql
STABLE
AS $$
    SELECT coalesce(auth.jwt() -> 'app_metadata' ->> 'role' = 'admin', false);
$$;

ALTER TABLE public.events ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.birthdays ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.holidays ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.event_registrations ENABLE ROW LEVEL SECURITY;

DO $$
DECLARE
    old_policy record;
BEGIN
    FOR old_policy IN
        SELECT schemaname, tablename, policyname
        FROM pg_policies
        WHERE schemaname = 'public'
          AND tablename IN ('events', 'birthdays', 'holidays', 'event_registrations')
    LOOP
        EXECUTE format(
            'DROP POLICY %I ON %I.%I',
            old_policy.policyname,
            old_policy.schemaname,
            old_policy.tablename
        );
    END LOOP;
END
$$;

REVOKE ALL ON public.events, public.birthdays, public.holidays, public.event_registrations
    FROM anon, authenticated;
GRANT SELECT ON public.events, public.birthdays, public.holidays TO anon, authenticated;
GRANT INSERT, UPDATE, DELETE ON public.events, public.birthdays, public.holidays TO authenticated;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.event_registrations TO authenticated;

DO $$
DECLARE
    sequence_name text;
BEGIN
    sequence_name := pg_get_serial_sequence('public.events', 'id');
    IF sequence_name IS NOT NULL THEN
        EXECUTE format('GRANT USAGE, SELECT ON SEQUENCE %s TO authenticated', sequence_name);
    END IF;
    sequence_name := pg_get_serial_sequence('public.events', 'event_id');
    IF sequence_name IS NOT NULL THEN
        EXECUTE format('GRANT USAGE, SELECT ON SEQUENCE %s TO authenticated', sequence_name);
    END IF;
    sequence_name := pg_get_serial_sequence('public.birthdays', 'id');
    IF sequence_name IS NOT NULL THEN
        EXECUTE format('GRANT USAGE, SELECT ON SEQUENCE %s TO authenticated', sequence_name);
    END IF;
    sequence_name := pg_get_serial_sequence('public.holidays', 'id');
    IF sequence_name IS NOT NULL THEN
        EXECUTE format('GRANT USAGE, SELECT ON SEQUENCE %s TO authenticated', sequence_name);
    END IF;
    sequence_name := pg_get_serial_sequence('public.event_registrations', 'id');
    IF sequence_name IS NOT NULL THEN
        EXECUTE format('GRANT USAGE, SELECT ON SEQUENCE %s TO authenticated', sequence_name);
    END IF;
END
$$;

REVOKE ALL ON FUNCTION public.is_buhlo_admin() FROM PUBLIC;
GRANT EXECUTE ON FUNCTION public.is_buhlo_admin() TO anon, authenticated;

DROP POLICY IF EXISTS "Public can read events" ON public.events;
CREATE POLICY "Public can read events"
    ON public.events FOR SELECT TO anon, authenticated USING (true);
DROP POLICY IF EXISTS "Admins manage events" ON public.events;
CREATE POLICY "Admins manage events"
    ON public.events FOR ALL TO authenticated
    USING (public.is_buhlo_admin()) WITH CHECK (public.is_buhlo_admin());

DROP POLICY IF EXISTS "Public can read birthdays" ON public.birthdays;
CREATE POLICY "Public can read birthdays"
    ON public.birthdays FOR SELECT TO anon, authenticated USING (true);
DROP POLICY IF EXISTS "Admins manage birthdays" ON public.birthdays;
CREATE POLICY "Admins manage birthdays"
    ON public.birthdays FOR ALL TO authenticated
    USING (public.is_buhlo_admin()) WITH CHECK (public.is_buhlo_admin());

DROP POLICY IF EXISTS "Public can read holidays" ON public.holidays;
CREATE POLICY "Public can read holidays"
    ON public.holidays FOR SELECT TO anon, authenticated USING (true);
DROP POLICY IF EXISTS "Admins manage holidays" ON public.holidays;
CREATE POLICY "Admins manage holidays"
    ON public.holidays FOR ALL TO authenticated
    USING (public.is_buhlo_admin()) WITH CHECK (public.is_buhlo_admin());

DROP POLICY IF EXISTS "Admins read registrations" ON public.event_registrations;
CREATE POLICY "Admins read registrations"
    ON public.event_registrations FOR SELECT TO authenticated
    USING (public.is_buhlo_admin());
DROP POLICY IF EXISTS "Admins manage registrations" ON public.event_registrations;
CREATE POLICY "Admins manage registrations"
    ON public.event_registrations FOR ALL TO authenticated
    USING (public.is_buhlo_admin()) WITH CHECK (public.is_buhlo_admin());

CREATE OR REPLACE FUNCTION public.get_public_event_participants()
RETURNS TABLE (event_id bigint, name text)
LANGUAGE sql
STABLE
SECURITY DEFINER
SET search_path = ''
AS $$
    SELECT registrations.event_id, registrations.name
    FROM public.event_registrations AS registrations
    ORDER BY registrations.registered_at, registrations.id;
$$;

CREATE OR REPLACE FUNCTION public.submit_event_registration(
    p_event_id bigint,
    p_registration_key uuid,
    p_name text,
    p_contact text DEFAULT 'не указан',
    p_notes text DEFAULT ''
)
RETURNS TABLE (registration_id bigint, event_id bigint, name text)
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = ''
AS $$
DECLARE
    event_limit integer;
    current_count bigint;
    saved_registration public.event_registrations%ROWTYPE;
BEGIN
    IF p_registration_key IS NULL
       OR length(trim(coalesce(p_name, ''))) NOT BETWEEN 1 AND 120
       OR length(coalesce(p_contact, '')) > 200
       OR length(coalesce(p_notes, '')) > 2000 THEN
        RAISE EXCEPTION 'Некорректные данные регистрации';
    END IF;

    SELECT coalesce(events."maxParticipants", 50)
    INTO event_limit
    FROM public.events AS events
    WHERE events.event_id = p_event_id
    FOR UPDATE;

    IF NOT FOUND THEN
        RAISE EXCEPTION 'Событие не найдено';
    END IF;

    SELECT count(*)
    INTO current_count
    FROM public.event_registrations AS registrations
    WHERE registrations.event_id = p_event_id;

    SELECT *
    INTO saved_registration
    FROM public.event_registrations AS registrations
    WHERE registrations.event_id = p_event_id
      AND registrations.registration_key = p_registration_key;

    IF FOUND THEN
        RETURN QUERY SELECT saved_registration.id, saved_registration.event_id, saved_registration.name;
        RETURN;
    END IF;

    IF current_count >= event_limit THEN
        RAISE EXCEPTION 'Мест на событие больше нет';
    END IF;

    INSERT INTO public.event_registrations (event_id, registration_key, name, contact, notes)
    VALUES (
        p_event_id,
        p_registration_key,
        trim(p_name),
        coalesce(nullif(trim(p_contact), ''), 'не указан'),
        coalesce(trim(p_notes), '')
    )
    RETURNING * INTO saved_registration;

    RETURN QUERY SELECT saved_registration.id, saved_registration.event_id, saved_registration.name;
END;
$$;

CREATE OR REPLACE FUNCTION public.replace_events(p_events jsonb)
RETURNS void
LANGUAGE plpgsql
SET search_path = ''
AS $$
BEGIN
    IF NOT public.is_buhlo_admin() OR p_events IS NULL OR jsonb_typeof(p_events) <> 'array' THEN
        RAISE EXCEPTION 'Недостаточно прав или неверный список событий';
    END IF;

    INSERT INTO public.events (
        event_id, title, date, time, location, description, recurrence, "maxParticipants"
    )
    SELECT
        item.event_id, item.title, item.date, nullif(item.time, ''),
        coalesce(item.location, ''), item.description, item.recurrence,
        coalesce(item."maxParticipants", 50)
    FROM jsonb_to_recordset(p_events) AS item(
        event_id bigint,
        title text,
        date date,
        time text,
        location text,
        description text,
        recurrence text,
        "maxParticipants" integer
    )
    ON CONFLICT (event_id) DO UPDATE SET
        title = EXCLUDED.title,
        date = EXCLUDED.date,
        time = EXCLUDED.time,
        location = EXCLUDED.location,
        description = EXCLUDED.description,
        recurrence = EXCLUDED.recurrence,
        "maxParticipants" = EXCLUDED."maxParticipants";

    DELETE FROM public.events AS events
    WHERE NOT EXISTS (
        SELECT 1
        FROM jsonb_to_recordset(p_events) AS item(event_id bigint)
        WHERE item.event_id = events.event_id
    );

    INSERT INTO public.event_registrations (
        event_id, registration_key, name, contact, notes, registered_at
    )
    SELECT
        item.event_id,
        gen_random_uuid(),
        trim(imported.person->>'name'),
        coalesce(nullif(trim(imported.person->>'contact'), ''), 'не указан'),
        coalesce(imported.person->>'notes', ''),
        coalesce(nullif(imported.person->>'registeredAt', '')::timestamptz, now())
    FROM jsonb_to_recordset(p_events) AS item(event_id bigint, participants jsonb)
    CROSS JOIN LATERAL jsonb_array_elements(
        CASE
            WHEN jsonb_typeof(item.participants) = 'array' THEN item.participants
            ELSE '[]'::jsonb
        END
    ) AS imported(person)
    WHERE jsonb_typeof(imported.person) = 'object'
      AND length(trim(coalesce(imported.person->>'name', ''))) BETWEEN 1 AND 120
      AND NOT EXISTS (
          SELECT 1 FROM public.event_registrations AS existing
          WHERE existing.event_id = item.event_id
      );

    IF pg_get_serial_sequence('public.events', 'event_id') IS NOT NULL THEN
        PERFORM setval(
            pg_get_serial_sequence('public.events', 'event_id'),
            coalesce((SELECT max(event_id) FROM public.events), 1),
            EXISTS (SELECT 1 FROM public.events)
        );
    END IF;
END;
$$;

CREATE OR REPLACE FUNCTION public.replace_birthdays(p_birthdays jsonb)
RETURNS void
LANGUAGE plpgsql
SET search_path = ''
AS $$
BEGIN
    IF NOT public.is_buhlo_admin() OR p_birthdays IS NULL OR jsonb_typeof(p_birthdays) <> 'array' THEN
        RAISE EXCEPTION 'Недостаточно прав или неверный список дней рождения';
    END IF;

    DELETE FROM public.birthdays WHERE true;
    INSERT INTO public.birthdays (date, name)
    SELECT item.date, item.name
    FROM jsonb_to_recordset(p_birthdays) AS item(date date, name text);
END;
$$;

CREATE OR REPLACE FUNCTION public.replace_holidays(p_holidays jsonb)
RETURNS void
LANGUAGE plpgsql
SET search_path = ''
AS $$
BEGIN
    IF NOT public.is_buhlo_admin() OR p_holidays IS NULL OR jsonb_typeof(p_holidays) <> 'array' THEN
        RAISE EXCEPTION 'Недостаточно прав или неверный список праздников';
    END IF;

    DELETE FROM public.holidays WHERE true;
    INSERT INTO public.holidays (date, name, event_type)
    SELECT item.date, item.name, coalesce(item.event_type, 'general')
    FROM jsonb_to_recordset(p_holidays) AS item(date text, name text, event_type text);
END;
$$;

REVOKE ALL ON FUNCTION public.get_public_event_participants() FROM PUBLIC;
REVOKE ALL ON FUNCTION public.submit_event_registration(bigint, uuid, text, text, text) FROM PUBLIC;
REVOKE ALL ON FUNCTION public.replace_events(jsonb) FROM PUBLIC;
REVOKE ALL ON FUNCTION public.replace_birthdays(jsonb) FROM PUBLIC;
REVOKE ALL ON FUNCTION public.replace_holidays(jsonb) FROM PUBLIC;
GRANT EXECUTE ON FUNCTION public.get_public_event_participants() TO anon, authenticated;
GRANT EXECUTE ON FUNCTION public.submit_event_registration(bigint, uuid, text, text, text) TO anon, authenticated;
GRANT EXECUTE ON FUNCTION public.replace_events(jsonb) TO authenticated;
GRANT EXECUTE ON FUNCTION public.replace_birthdays(jsonb) TO authenticated;
GRANT EXECUTE ON FUNCTION public.replace_holidays(jsonb) TO authenticated;

DO $$
DECLARE
    sequence_name text := pg_get_serial_sequence('public.events', 'event_id');
BEGIN
    IF sequence_name IS NOT NULL THEN
        PERFORM setval(
            sequence_name,
            coalesce((SELECT max(event_id) FROM public.events), 1),
            EXISTS (SELECT 1 FROM public.events)
        );
    END IF;
END
$$;

NOTIFY pgrst, 'reload schema';
